#!/usr/bin/env zsh

typeset -g __ZEST_MAIN_FILE
typeset -g __ZEST_ROOT_DIR
typeset -g __ZEST_EVAL_CONTEXT
typeset -ga __ZEST_FUNCTION_DIRS
typeset -ga __ZEST_FUNCTIONS


__ZEST_EVAL_CONTEXT=$ZSH_EVAL_CONTEXT
print -v __ZEST_MAIN_FILE -P %x

__ZEST_MAIN_FILE=${__ZEST_MAIN_FILE:A}
__ZEST_ROOT_DIR=${__ZEST_MAIN_FILE:h}
__ZEST_FUNCTION_DIRS=($__ZEST_ROOT_DIR/src/**/*(/N))

__zest_welcome_message() {
  emulate -L zsh
  autoload -Uz zest_print

  local temp
  local buf
  local nl=$'\x0a'

  zest_print -n -v temp --color=green "%Bzest%b "
  buf+=$temp
  zest_print -n -v temp --color=cyan "now initialized!"
  buf+=$temp$nl
  zest_print -n -v temp --color=cyan "Execute "
  buf+=$temp
  zest_print -n -v temp --color=white "%Brun_tests%b"
  buf+=$temp
  zest_print -n -v temp --color=cyan " to run any defined "
  buf+=$temp
  zest_print -n -v temp --color=white "%Btest_*%b"
  buf+=$temp
  zest_print -n -v temp --color=cyan " functions"
  buf+=$temp

  print -- $buf
}

__zest_run_once() {
  emulate -L zsh

  () {
    emulate -L zsh

    setopt errreturn

    local subject

    for subject in $@; do
      if [[ $subject = -* ]]; then
        zest_print --color=red "Unknown option: $subject"
        return 1
      fi

      source $subject
    done
  } $@ || return 1

  run_tests
}

zest() {
  emulate -L zsh

  setopt extendedglob
  setopt errreturn

  autoload -Uz zest_print

  local was_sourced=false

  if [[ $__ZEST_EVAL_CONTEXT = *:file ]]; then
    was_sourced=true
  fi

  fpath+=($__ZEST_FUNCTION_DIRS)
  __ZEST_FUNCTIONS=(${~__ZEST_FUNCTION_DIRS/%/***/[^.](#c1,)(#qN.:t)})
  autoload -Uz $__ZEST_FUNCTIONS

  zest_initialize

  if $was_sourced; then
    if [[ -o interactive ]]; then
      __zest_welcome_message
    fi
    return 0
  fi

  if (( $#@ > 0 )); then
    __zest_run_once $@
    return $?
  else
    zmodload zsh/mapfile
    zmodload -F zsh/files b:zf_rm

    local temp=$(mktemp -d)
    local currentdir=$PWD
    local user_rc=""
    local -a zshrc_path=(${ZDOTDIR:-$HOME}/.zshrc(N:P))

    if (( $#zshrc_path )); then
      user_rc=${mapfile[$zshrc_path[1]]}
    fi

    builtin cd $temp &>/dev/null

    mapfile[.zshrc]="
		$user_rc
		source $__ZEST_MAIN_FILE
		builtin cd $currentdir &>/dev/null
		"

    {
      ZDOTDIR=$PWD zsh --interactive --zle --rcs
      } always {
      integer nested_rc=$?
      builtin cd $currentdir &>/dev/null
      zf_rm -rf $temp
      print -P "%F{cyan}Quitting%f %F{green}%Bzest%b%f%F{cyan}...%f"
      return $nested_rc
    }
  fi
}

zest $@
